export const metadata = {
    title: "Blog",
    description: "Generated by create next app"
};

export default function BlogLayout({ children }: { children: React.ReactNode }) {
    return (
        <div>
        {children}
        </div>
    );
}