export const metadata = {
    title: "Blog",
    description: "Generated by create next app"
};

export default function BlogLayout({ children }: { children: React.ReactNode }) {
    
    return (
            <div className="childFirst min-w-screen min-h-screen my-10 mx-10">
            {children}
            </div>
    );
}