import FooterNavBar from '@/components/footer/footerNavbar';
import Navbar from '../../../components/nav/Navbar';

export const metadata = {
    title: "Blog",
    description: "Generated by create next app"
};

export default function BlogLayout({ children }: { children: React.ReactNode }) {
    
    return (
        <>
        <Navbar />
            <div className="childFirst min-w-screen min-h-screen my-10 mx-10">
            {children}
            </div>
        <FooterNavBar />
        </>
    );
}