import type { Metadata } from "next";
import { Cormorant_Garamond, Poppins, Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Navbar from '../components/nav/Navbar';
import FooterNavBar from "@/components/nav/footer/footerNavbar";
import { SpeedInsights } from "@vercel/speed-insights/next";
import React from "react";

const inter = Inter({ subsets: ["latin"] });

const cormorantGaramond = Cormorant_Garamond({ 
  subsets: ["latin"],
  variable: "--font-cormorant-garamond",
  weight: ["400"],
});

const poppins = Poppins({ 
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["400", "600"],
});

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${cormorantGaramond.variable} ${poppins.variable}`}>
        <div className="first">
        <SpeedInsights/>
        <Providers>
          <Navbar />
          <main className="min-h-screen">
            {children}
          </main>
          <FooterNavBar />
        </Providers>
        </div>
      </body>
    </html>
  );
}