export const metadata = {
    title: "Contact",
    description: "Generated by create next app"
};

export default function ContactLayout({ children }: { children: React.ReactNode }) {
    return (
        <div className="childFirst min-w-screen min-h-screen mt-10 mx-10">
        {children}
        </div>
    );
}