export const metadata = {
    title: "Projects",
    description: "Generated by create next app"
};

export default function ProjectsLayout({ children }: { children: React.ReactNode }) {
    return (
        <div className="childFirst min-w-screen min-h-screen my-10 mx-20">
        {children}
        </div>
    );
}